global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets: ['node-exporter:9100']
 - job_name: indexer
   static_configs:
    - targets: [ lister:8080, consumer:8080, record-indexer:8080, pds-discovery:8080 ]
 - job_name: db
   static_configs:
    - targets: ['query-exporter:9560']
